### ISSUE TITLE
tomcat cdmp.jsp http 500

### ISSUE THREAD

**Issue by aJax-me** [Ch1ngg/CaidaoMitmProxy#2]
HTTP Status 500 – Internal Server Error
Type 异常报告

消息 在 [271] 行处理 [/cdmp.jsp] 时发生异常

描述 服务器遇到一个意外的情况，阻止它完成请求。

Exception

org.apache.jasper.JasperException: 在 [271] 行处理 [/cdmp.jsp] 时发生异常

268: 			return null;
269: 		Cipher cipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
270: 		cipher.init(Cipher.DECRYPT_MODE, new SecretKeySpec(key.getBytes(cs), "DES"));
271: 		bytes = cipher.doFinal(bytes);
272: 		return new String(bytes, cs);
273: 	}
274:

**Comment by Ch1ngg** [comment]
此项目已经在蚁剑写了相关插件，请前往获取，不在维护此项目
